Windows support
ssalonen/libcec-sys pull request #15
Opened 2022-07-11 18:40 UTC by ok-nick

## Solves #13 
Support for Windows is fairly straightforward and libcec takes care of most of the work via their batch files.

### Prerequisites:
* Visual Studio 2013 to 2019 w/ Desktop Development with C++ and Universal Windows Platform development
* cmake 3.12+
* **and possibly more**

### TODO
- [ ] Find and run the `vsvarsall.bat` file from Visual Studio before doing the smoke test to initialize the compiler's env variables.
- [ ] Correctly link with `cecc.h` for smoke test.
- [ ] Automatically find VS version and platform type (the batch files should take care of it auto, but this doesn't seem to work?).
- [ ] Automatically choose between `Release` and `Debug` build.

For now, I've hardcoded a few parameters just for testing.

2022-07-12 04:18 UTC, ssalonen commented
The idea of smoke test is to compile a small c application, including headers from cec project and linking to libcec shared library.

Note that intent is not utilize vendor library in any way here.

Even on linux this does not work by default, as the directories are not findable in the common distros without extra flags/environmental variables.

However, when setting those environment variables, it offers the user a viable option without pkg config (or without pkg config files). You can find concrete example from github CI flow where this is tested.

Are there similar same environment variables on windows? Is there precompiled distribution of libcec for windows?

2022-07-12 04:28 UTC, ssalonen commented
Based on quick googling visual studio might utilize these directories and env variables 

- PATH for shared libs (dll)
- INCLUDE for headers https://docs.microsoft.com/en-us/cpp/preprocessor/hash-include-directive-c-cpp

If this is correct, it makes sense to keep the same smoke test with windows as well.

Is this something you can try out at some point? I am not sure how hard would it be to setup windows github action to test all this...

2022-07-17 00:24 UTC, ok-nick commented
Yes, that sounds about right. The build script runs every compilation as to why I thought the smoke tests would fix it. There must be something in the `libcec` build script causing a file to be modified at the last second.

I'll have to check out the github actions once everything looks good.

2022-07-25 22:27 UTC, ok-nick commented
I added a basic Windows test for vendored builds and it works well. The reason the `--release` flag was added to `cargo test` is because a debug build requires Python with debug binaries installed, which is not something github actions have by default.

I'm not sure what `cross` does or the point of using it in your situation, so I'm not sure if it is needed for CI on Windows?

2022-07-26 10:57 UTC, ssalonen commented
I understand the issue without the --release. Ideally it would make sense not use --release as some of the rust assertions are not active then. 

On the other hand, there are no tests at all in libcec-sys, so it's not a big deal here, more of a topic for cec-rs.

Can we not compile the vendored build always as non-debug? I am not sure but is this how it goes with nix builds?
-------

Cross is not needed in windows here. In fact, it does not seem to support msvc, only gnu compiler https://github.com/cross-rs/cross

Cross is used for cross compiling and running the tests with different architectures. My thinking was that this library might be used with different type of embedded environments / devices, so why not introduce the  compilation check for it as well. However, since there is little platform specific code, it is not doing much now...

2022-07-26 11:04 UTC, ssalonen commented
BTW, on windows, does this build the library as statically linked to the application binary? 

Should it? I am not sure which way is the preferred way on windows.

2022-07-26 20:17 UTC, ok-nick commented
We could technically always compile libcec in release mode, although I'm assuming it may cancel out some of the debug assertions and other nice features. I guess the same also goes for Rust, so I'll add the correct python installation to CI.

As for Cross, if it is no longer useful, do you think we should remove it?

By default, [according to here](https://doc.rust-lang.org/rustc/command-line-arguments.html#option-l-link-lib), it will compile dynamically before statically. I don't see any use for a dynamic library, especially when everything Rust is pretty much compiled statically and upstream crates will probably expect this to just "work," so I'll add an explicit check.

2022-07-26 21:49 UTC, ok-nick commented
I keep running into issues statically linking. When linking against `cec.lib`, it ends up linking back to `cec.dll`. When linking against `cec-static.lib`, it explodes with linking errors.

2022-07-27 00:32 UTC, ok-nick commented
There is also no easy way to find installed Visual Studio versions. `cc` seems capable of this, but it only exposes a method for getting the latest installed version (if they have 2022 then we can't know if they have 2019), [check here](https://docs.rs/cc/latest/src/cc/windows_registry.rs.html#114).

An alternative would be to use the `vswhere` utility, which comes preinstalled with Visual Studio 2017+. Since `libcec` theoretically supports down to 2013, we would have to manually download the executable. In addition, we would have to pull in [this dependency](https://github.com/FaultyRAM/vswhere-rs), which unfortunately hasn't been maintained in over 4 years. I'm not sure if there is anything else.

2022-07-27 05:20 UTC, ssalonen commented
When testing static linking, did you remove the cargo:rustc-link-lib=cec? I think it is the thing that adds the link?

2022-07-27 05:22 UTC, ok-nick commented
No, I kept it as is and even tried changing it to `cec-static` as well as adding the explicit `static` kind as described in the docs.

2022-07-27 05:24 UTC, ok-nick commented
You may be able to see for yourself if you fork my branch and run the CI. Tomorrow... well, later today for me, I could send u the output log I get.

2022-07-27 06:23 UTC, ssalonen commented
Yes, I would expect static linking with windows while keeping dynamic linking with Linux. With Linux libcec is often easily available from distribution repos. 

We can always make this configurable as well, if need arises in the future.

2022-07-27 07:53 UTC, ssalonen commented
> There is also no easy way to find installed Visual Studio versions. `cc` seems capable of this, but it only exposes a method for getting the latest installed version (if they have 2022 then we can't know if they have 2019), [check here](https://docs.rs/cc/latest/src/cc/windows_registry.rs.html#114).
> 
> 
> 
> An alternative would be to use the `vswhere` utility, which comes preinstalled with Visual Studio 2017+. Since `libcec` theoretically supports down to 2013, we would have to manually download the executable. In addition, we would have to pull in [this dependency](https://github.com/FaultyRAM/vswhere-rs), which unfortunately hasn't been maintained in over 4 years. I'm not sure if there is anything else.
> 
> Edit: Although `libcec` seems to compile fine with 2017, the docs state it only supports 2019+ so there could possibly be side effects. We should probably only support 2019 and if it's not installed, `libcec` will automatically output a corresponding error.

Was this resolved? Why is not ok to utilize the latest installed version?

2022-07-27 09:48 UTC, ssalonen commented
Regarding cross:

On second thought it makes sense to ensure the build works, e.g. with arm (raspberry pi). This way we would get early failure already with libcec-sys, not with cec-rs, in case the build needs some adjustment.

With windows we are only looking at non-gnu compilation (not mingw), thus, cross is not usable there.

2022-07-27 14:17 UTC, ok-nick commented
`libcec` does not compile with Visual Studio 2022. It does compile with 2017-2019 (as far as I've tested) although the docs state it only supports 2019+. I will make it so you must have 2019 installed.

2022-07-28 05:45 UTC, ok-nick commented
Should definitely cache python, it takes 1-2 minutes to install.

2022-07-28 06:55 UTC, ssalonen commented
Thank you! This has been quite some work but really great to see windows supported as well 🙏

2022-07-31 13:02 UTC, ssalonen requested changes
Review comments. Also, don't forget to update Readme (there is a statement on win support) and changelog

2022-07-31 14:46 UTC, ok-nick commented on build/build.rs
> +            dst.join(LIBCEC_BUILD).join("amd64").display()
Yes

2022-07-31 14:51 UTC, ok-nick commented on build/build.rs
> +        compile_vendored_platform(&dst);
I could also put it behind a `#[cfg(target_os = "linux")]` macro.

2022-07-31 15:13 UTC, ok-nick commented on build/build.rs
> +    println!("cargo:rerun-if-env-changed=INCLUDE");
Visual Studio sets env variables when `vsvarsall.bat` is ran, but that's automatically ran by `libcec`. I can't seem to find any indication of env variables being set on installation. The best we can do is check if the installation path exists although that doesn't seem possible with `cargo`.

2022-08-01 19:11 UTC, ok-nick commented on build/build.rs
> +        Command::new("cmd")
`compile_vendored_libccec`*

2022-08-02 04:41 UTC, ssalonen reviewed
One more final comment, then we are good to merge!

2022-08-02 04:41 UTC, ssalonen commented on build/build.rs
> +const ARCHITECTURE: &str = if cfg!(target_pointer_width = "64") {
Should we move this windows specific constant to the windows build function (only place where it is used?)

I think it would avoid any confusion to reader as many more architectures are supported with Linux.

2022-08-02 04:48 UTC, ok-nick commented on build/build.rs
> +const ARCHITECTURE: &str = if cfg!(target_pointer_width = "64") {
I agree and I initially had that, but for [line 207](https://github.com/ok-nick/libcec-sys/blob/7fd8d96c2e3fed4ec32b0c4cb72190606badf546/build/build.rs#L207) we would then need to use individual blocks for each configuration.

We could also do two platform-specific variables right above the `println`. It's still not pretty, but better?

2022-08-02 04:52 UTC, ok-nick commented on build/build.rs
>      println!("cargo:rerun-if-env-changed=LD_LIBRARY_PATH");
I was thinking of creating a very simple macro for all the boilerplate, good idea?

2022-08-02 05:37 UTC, ssalonen commented on build/build.rs
> +const ARCHITECTURE: &str = if cfg!(target_pointer_width = "64") {
Allright, did not see line 207! I think we do not need `ARCHITECTURE` with linux so how about renaming simply as `ARCHITECTURE_WIN` for now?

2022-08-02 05:37 UTC, ssalonen commented on build/build.rs
>      println!("cargo:rerun-if-env-changed=LD_LIBRARY_PATH");
what would this macro do? what do you mean by the boilerplate in this context?

2022-08-02 13:08 UTC, ok-nick commented on build/build.rs
>      println!("cargo:rerun-if-env-changed=LD_LIBRARY_PATH");
Instead of `println!("cargo:rerun-if-env-changed=LD_LIBRARY_PATH");`, it could be `watch_env!("LD_LIBRARY_PATH");`

2022-08-02 13:22 UTC, ssalonen commented on build/build.rs
>      println!("cargo:rerun-if-env-changed=LD_LIBRARY_PATH");
Well there is a crate for it, https://docs.rs/cargo-emit/latest/cargo_emit/ (I stumbled on this while googling something)

Personally, I opted for not introducing additional dependency as the benefit is quite minimal (obfuscates the intent a bit, as the crate is not well known (?). My understanding is that println approach is fairly common in build scripts).

2022-08-02 13:36 UTC, ok-nick commented on build/build.rs
>      println!("cargo:rerun-if-env-changed=LD_LIBRARY_PATH");
I agree, it probably is best to leave it simple and clear. No need for fancy macros or pulling in another dependency.

2022-08-02 17:56 UTC, ok-nick commented on build/build.rs
> +const ARCHITECTURE: &str = if cfg!(target_pointer_width = "64") {
We could do that but imo it sounds a little hacky.. Maybe instead we could create a `link_libcec` function for Windows and Linux? That doesn't make it any less code, but it's definitely more clear and ergonomic for when more platforms are supported.

2022-08-06 07:27 UTC, ssalonen approved these changes

2022-08-06 07:28 UTC, ssalonen commented
Big thank you!

2022-08-06 07:28 UTC, merged